name: Angular CI deploy
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
        with:
          github_access_token: '${{ secrets.TASKMANAGER  }}'
          build_configuration: production
          base_href: /task-manager/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/TaskManager
